# Source path environment settings
[[ -r ~/.dotfiles/shell/.path ]] && . ~/.dotfiles/shell/.path
[[ -r ~/.dotfiles/shell/.profile_env ]] && . ~/.dotfiles/shell/.profile_env

# Add .fpath to $FPATH
local local_fpath_loc="$HOME/.fpath"
local synced_fpath_loc="$HOME/.dotfiles/zsh/.fpath"
[[ :$PATH: != *:"$local_fpath_loc":* ]] && [[ -d "$local_fpath_loc" ]] && export FPATH=$FPATH:"$local_fpath_loc"
[[ :$PATH: != *:"$synced_fpath_loc":* ]] && [[ -d "$synced_fpath_loc" ]] && export FPATH=$FPATH:"$synced_fpath_loc"
