# zshenv is *always* loaded, so it's as lightweight as possible and doesn't source the utilities

# Source path environment settings
[[ -r $DOTFILES/profile.d/paths.sh ]] && source $DOTFILES/profile.d/paths.sh
[[ -r $DOTFILES/profile.d/env.sh ]] && source $DOTFILES/profile.d/env.sh

# Add to FPATH
local local_fpath_loc="$HOME/.fpath"
local synced_fpath_loc="$DOTFILES/zsh.d/fpath"
[[ -d "$local_fpath_loc" ]] && fpath+="$local_fpath_loc"
[[ -d "$synced_fpath_loc" ]] && fpath+="$synced_fpath_loc"
