############
# Autoload #
############

# Load Zim
source_file ${ZDOTDIR:-$HOME}/.zim/init.zsh

# Load plugins
source_file $HOME/.dotfiles/zsh.d/zplugrc

# Autoload functions
autoload -U zcalc zsh-mime-setup
zsh-mime-setup

# Source profile.d, ignoring what .zshenv has already sourced
source_dir $HOME/.dotfiles/profile.d "path.sh,env.sh"

# Source zsh.d
source_dir $HOME/.dotfiles/zsh.d zsh

# FIXME: add npm completion (see https://github.com/sorin-ionescu/prezto/blob/master/modules/node/init.zsh#L23)
# FIXME: add prezto's osx module as a git submodule


##############
# Completion #
##############

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # Case insensitive
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd' # Better killall completion
zstyle ':completion:*' verbose yes
source_file ~/.pyenv/completions/pyenv.zsh # Pyenv

###########
# Options #
###########

setopt VI # Vim key bindings
setopt CORRECT # Correct commands
setopt COMPLETE_IN_WORD # Tab complete in word
unsetopt COMPLETE_ALIASES # Don't expand aliases to allow for completion after aliases
setopt RM_STAR_WAIT # Sanity check for rm *
setopt EXTENDED_GLOB # Use extended globbing
setopt NO_CASE_GLOB # Case insensitive glob
setopt RC_EXPAND_PARAM # Expand arrays
setopt IGNORE_EOF # Force 'exit' to logout
setopt INTERACTIVECOMMENTS # Allow for comments on command line

KEYTIMEOUT=1 # Shorten vi mode delay

#####################
#      History      #
# (see zim.history) #
#####################

setopt APPEND_HISTORY # Don't overwrite history
setopt HIST_REDUCE_BLANKS


################
# After hooks #
###############

# Source profile.d/after
source_dir $HOME/.dotfiles/profile.d/after

# Source zsh.d/after
source_dir $HOME/.dotfiles/zsh.d/after zsh
