##### FIRST THINGS FIRST #####

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    fortune -s
    print
  fi
fi


##### Autoload #####

# Load zplug and plugins
[[ -r ~/.zplug/init.zsh ]] && . ~/.zplug/init.zsh
zplug "eventi/noreallyjustfuckingstopalready"

autoload -U zcalc zsh-mime-setup
zsh-mime-setup

# Source Zim
[[ -r "${ZDOTDIR:-$HOME}/.zim/init.zsh" ]] && . ${ZDOTDIR:-$HOME}/.zim/init.zsh


# Source aliases, functions, and shell plugins
[[ -r ~/.dotfiles/shell/.alias ]] && . ~/.dotfiles/shell/.alias
[[ -r ~/.dotfiles/shell/zsh/.alias ]] && . ~/.dotfiles/shell/zsh/.alias
[[ -r ~/.dotfiles/shell/.function ]] && . ~/.dotfiles/shell/.function
[[ -r ~/.dotfiles/shell/.plugin ]] && . ~/.dotfiles/shell/.plugin

# Language version managers
[[ -r "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh" # NVM
[[ -r "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # RVM
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)" # Pyenv-virtualenv

# FIXME: add npm completion (see https://github.com/sorin-ionescu/prezto/blob/master/modules/node/init.zsh#L23)
# FIXME: add prezto's osx module as a git submodule





##### Misc #####
setopt VI # Vim key bindings
setopt CORRECT # Correct commands
setopt RM_STAR_WAIT # Sanity check for rm *
setopt EXTENDED_GLOB # Use extended globbing
setopt NO_CASE_GLOB # Case insensitive glob
setopt RC_EXPAND_PARAM # Expand arrays
setopt IGNORE_EOF # Force 'exit' to logout
setopt COMPLETE_IN_WORD # Tab complete in word
unsetopt COMPLETE_ALIASES # Don't expand aliases to allow for completion after aliases

KEYTIMEOUT=1 # Shorten vi mode delay


##### Completion #####
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # Case insensitive
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd' # Better killall completion
zstyle ':completion:*' verbose yes
[[ -r ~/.pyenv/completions/pyenv.zsh ]] && . ~/.pyenv/completions/pyenv.zsh # Pyenv

# In case git completion ever gets slow, turn this on:
# function __git_files {
#   _wanted files expl 'local files' _files # Just use all files in the directory instead of being based on git status
# }


##### History #####
# See zim.history
setopt APPEND_HISTORY # Don't overwrite history
setopt HIST_REDUCE_BLANKS


##### Non built-ins #####

################
# After hooks #
###############

##### Zplug loading #####
#
# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
# Source profile.d/after
source_dir $HOME/.dotfiles/profile.d/after

zplug load
# Source zsh.d/after
source_dir $HOME/.dotfiles/zsh.d/after zsh
