" Use Vim settings, rather then Vi settings
" This must be first, because it changes other options as a side effect.
set nocompatible

" Set the all important colorscheme AS SOON AS POSSIBLE
colorscheme solarized
set background=dark
if $TERM_PROGRAM =~ "iTerm" "Get true colour support
  " set termguicolors
endif

set backupcopy=yes

" Show incomplete commands
set showcmd

" Use select mode when making mouse selections"
set selectmode=mouse,key

" Use OSX shift movements
if has("gui_macvim")
    let macvim_hig_shift_movement = 1
endif

" Resource .vimrc
:nnoremap <leader>sv :source $MYVIMRC<cr>

" Edit .vimrc (in ~/.dotfiles folder)
:nnoremap <leader>ev :vsplit ~/.dotfiles/.vimrc.after<cr>

" Set leader key to ,
let mapleader = ","

" Allow . operator in visual mode
vnoremap . :normal.<CR>

" Map F1 key to ESC
noremap <F1> <Esc>
inoremap <F1> <Esc>

" Map F2 key to NERDTree
nnoremap <F2> :NERDTreeToggle<cr>

" Map F5 key to UndoTree
nnoremap <F5> :UndotreeToggle<cr>

" Map Set F6 key to SyntasticErrors
nnoremap <silent> <F6> :<C-u>call ToggleErrors()<CR>

" Map Set F7 key to Git blame
nnoremap <F7> :Gblame<cr>

" Map window split commands
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" FIXME: remove and just use gU / gUU instead
" Map insert-mode uppercase word
inoremap <C-c> <esc>viwU<esc>ea
nnoremap <C-c> viwU<esc>e

" Swap directions of # and *
nnoremap # *
vnoremap # *
nnoremap * #
vnoremap * #

" Set find path to be dir of open file, current dir, and any dirs under current dir
set path=.,,**

" FIXME: move to autogroups
" Add .js, .css, and .scss extensions to files
set suffixesadd+=.js,.css,.scss

" Set natural split opening
set splitbelow
set splitright

" Indent settings
set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=4    " Indents will have a width of 4

set softtabstop=4   " Sets the number of columns for a TAB

set expandtab       " Expand TABs to spaces

set smarttab        " Make "tab" insert indents instead of tabs at the beginning of a line

" Set textwidth at 100
set textwidth=100

" Start scrolling slightly before the cursor reaches an edge
set scrolloff=3
set sidescrolloff=5

set sidescroll=1    " Scroll sideways a character at a time, rather than a screen at a time

" Allow motions and back-spacing over line-endings etc
set backspace=indent,eol,start
set whichwrap=h,l,b,<,>,~,[,]

" Only insert one space when J(oining)
set nojoinspaces

" File types handling
" Enable filetype detection:
filetype on
filetype plugin on
filetype indent on " file type based indentation

augroup custom_filetypes
    au!
    au BufRead,BufNewFile *.jsx setlocal filetype=javascript
    au BufRead,BufNewFile *.jsonld setlocal filetype=json
    au BufRead,BufNewFile *.cshtml setlocal filetype=html
    au BufRead,BufNewFile *.cshtml_ setlocal filetype=html
    au BufRead,BufNewFile *.scss setlocal filetype=css
    au BufRead,BufNewFile *.md setlocal filetype=markdown
augroup END

augroup js_filetype
    au!
    au BufRead,BufNewFile *.js setlocal shiftwidth=2 tabstop=2 softtabstop=2
    au BufRead,BufNewFile *.jsx setlocal shiftwidth=2 tabstop=2 softtabstop=2
augroup END

augroup py_filetype
    au!
    au BufRead,BufNewFile *.py setlocal textwidth=79 colorcolumn=80 foldlevel=20

    " Fold and unfold using enter
    au BufEnter *.py nnoremap <buffer> <Enter> @=(foldlevel('.')?'za':"\r")<CR>

    " Sometimes necessary for SimpylFold
    au BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
    au BufWinLeave *.py setlocal foldexpr< foldmethod<
augroup END

augroup md_filetype
    au!
    au BufRead,BufNewFile *.md setlocal textwidth=100 colorcolumn=101
augroup END

augroup rst_filetype
    au!
    au BufRead,BufNewFile *.rst setlocal textwidth=79 colorcolumn=80
augroup END

augroup make_filetype
    au!
    au FileType make setlocal noexpandtab shiftwidth=8 softtabstop=0
augroup END

augroup json_filetype
    au!
    au BufRead,BufNewFile *.json setlocal shiftwidth=2 tabstop=2 softtabstop=2
augroup END

augroup yml_filetype
    au!
    au BufRead,BufNewFile *.yml setlocal shiftwidth=2 tabstop=2 softtabstop=2
augroup END

" Don't conceal json syntax
let g:vim_json_syntax_conceal = 0

" Allow JSX syntax in .js files
let g:jsx_ext_required = 0

" Signify config
let g:signify_vcs_list= [ 'git' ]

" Folding config
" Python
let g:SimpylFold_docstring_level = 20
let g:SimpylFold_docstring_preview = 1
let g:SimpylFold_fold_import = 0

" Syntastic configs
command Syncheck SyntasticCheck
command Synreset SyntasticReset
command Synclose lclose

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 5

" Use validator for HTML syntastic
let g:syntastic_html_checkers = ['htmlhint']

" Use ESLint for JS syntastic
let g:syntastic_javascript_checkers = ['eslint']

" Use Flake8 for Python syntastic
let g:syntastic_python_checkers = ['flake8']

" Toggle SyntasticErrors
function! ToggleErrors()
    let old_last_winnr = winnr('$')
    lclose
    if old_last_winnr == winnr('$')
        " Nothing was closed, open syntastic error location panel
        Errors
    endif
endfunction

" Editorconfig excludes files over git and scp
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

if has('nvim')
    let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1 " Let cursor shape change on insert
    " Will probably be useful to look at https://github.com/neovim/neovim/issues/2048#issuecomment-98307896
endif
